import { WeatherData, WeatherSettings } from '@/types';

// You can use any weather API service like OpenWeatherMap, WeatherAPI, etc.
// For this example, I'll use a mock service that you can replace with a real API
const WEATHER_API_KEY = process.env.NEXT_PUBLIC_WEATHER_API_KEY || 'your-api-key';
const WEATHER_API_BASE_URL = 'https://api.weatherapi.com/v1';

export class WeatherService {
  private static instance: WeatherService;
  private cache: Map<string, { data: WeatherData; timestamp: number }> = new Map();
  private readonly CACHE_DURATION = 10 * 60 * 1000; // 10 minutes

  private constructor() {}

  static getInstance(): WeatherService {
    if (!WeatherService.instance) {
      WeatherService.instance = new WeatherService();
    }
    return WeatherService.instance;
  }

  async getCurrentWeather(location: string, settings: WeatherSettings): Promise<WeatherData> {
    const cacheKey = `${location}-${settings.unit}`;
    const cached = this.cache.get(cacheKey);
    
    if (cached && Date.now() - cached.timestamp < this.CACHE_DURATION) {
      return cached.data;
    }

    try {
      // For demo purposes, using mock data
      // Replace this with actual API call
      const weatherData = await this.fetchWeatherData(location, settings);
      
      this.cache.set(cacheKey, {
        data: weatherData,
        timestamp: Date.now()
      });

      return weatherData;
    } catch (error) {
      console.error('Error fetching weather data:', error);
      throw new Error('Failed to fetch weather data');
    }
  }

  private async fetchWeatherData(location: string, settings: WeatherSettings): Promise<WeatherData> {
    // Mock weather data for demonstration
    // Replace this with actual API call to your preferred weather service
    const mockWeatherData: WeatherData = {
      location: {
        name: location,
        country: 'US',
        lat: 40.7128,
        lon: -74.0060,
        timezone: 'America/New_York',
        localtime: new Date().toISOString(),
      },
      current: {
        temp_c: 22,
        temp_f: 72,
        condition: {
          text: 'Partly cloudy',
          icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
          code: 1003,
        },
        humidity: 65,
        wind_kph: 15,
        wind_mph: 9,
        wind_dir: 'NE',
        pressure_mb: 1013,
        feelslike_c: 24,
        feelslike_f: 75,
        uv: 5,
        visibility_km: 10,
        cloud: 40,
        is_day: true,
      },
      forecast: [
        {
          date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
          day: {
            maxtemp_c: 25,
            maxtemp_f: 77,
            mintemp_c: 18,
            mintemp_f: 64,
            avgtemp_c: 21.5,
            avgtemp_f: 70.7,
            maxwind_kph: 20,
            maxwind_mph: 12,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 60,
            daily_chance_of_rain: 10,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            uv: 7,
          },
          astro: {
            sunrise: '06:30 AM',
            sunset: '07:45 PM',
            moonrise: '08:15 PM',
            moonset: '06:45 AM',
            moon_phase: 'Waxing Crescent',
            moon_illumination: '45',
          },
          hour: [
            {
              time: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
              temp_c: 23,
              temp_f: 73,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_kph: 12,
              wind_mph: 7,
              wind_dir: 'NE',
              pressure_mb: 1012,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 35,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 23,
              windchill_f: 73,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 15,
              dewpoint_f: 59,
              will_it_rain: 0,
              chance_of_rain: 5,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 18,
              gust_mph: 11,
              uv: 6,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
              temp_c: 24,
              temp_f: 75,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_kph: 10,
              wind_mph: 6,
              wind_dir: 'E',
              pressure_mb: 1011,
              precip_mm: 0,
              precip_in: 0,
              humidity: 58,
              cloud: 20,
              feelslike_c: 26,
              feelslike_f: 79,
              windchill_c: 24,
              windchill_f: 75,
              heatindex_c: 26,
              heatindex_f: 79,
              dewpoint_c: 14,
              dewpoint_f: 57,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 15,
              gust_mph: 9,
              uv: 7,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
              temp_c: 25,
              temp_f: 77,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_kph: 8,
              wind_mph: 5,
              wind_dir: 'SE',
              pressure_mb: 1010,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 15,
              feelslike_c: 27,
              feelslike_f: 81,
              windchill_c: 25,
              windchill_f: 77,
              heatindex_c: 27,
              heatindex_f: 81,
              dewpoint_c: 13,
              dewpoint_f: 55,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 12,
              gust_mph: 7,
              uv: 8,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
              temp_c: 26,
              temp_f: 79,
              condition: {
                text: 'Sunny',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_kph: 6,
              wind_mph: 4,
              wind_dir: 'S',
              pressure_mb: 1009,
              precip_mm: 0,
              precip_in: 0,
              humidity: 52,
              cloud: 10,
              feelslike_c: 28,
              feelslike_f: 82,
              windchill_c: 26,
              windchill_f: 79,
              heatindex_c: 28,
              heatindex_f: 82,
              dewpoint_c: 12,
              dewpoint_f: 54,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 10,
              gust_mph: 6,
              uv: 9,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
              temp_c: 25,
              temp_f: 77,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_kph: 8,
              wind_mph: 5,
              wind_dir: 'SW',
              pressure_mb: 1008,
              precip_mm: 0,
              precip_in: 0,
              humidity: 58,
              cloud: 25,
              feelslike_c: 27,
              feelslike_f: 81,
              windchill_c: 25,
              windchill_f: 77,
              heatindex_c: 27,
              heatindex_f: 81,
              dewpoint_c: 14,
              dewpoint_f: 57,
              will_it_rain: 0,
              chance_of_rain: 10,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 12,
              gust_mph: 7,
              uv: 6,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
              temp_c: 24,
              temp_f: 75,
              condition: {
                text: 'Cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_kph: 10,
              wind_mph: 6,
              wind_dir: 'W',
              pressure_mb: 1007,
              precip_mm: 0,
              precip_in: 0,
              humidity: 65,
              cloud: 45,
              feelslike_c: 26,
              feelslike_f: 79,
              windchill_c: 24,
              windchill_f: 75,
              heatindex_c: 26,
              heatindex_f: 79,
              dewpoint_c: 16,
              dewpoint_f: 61,
              will_it_rain: 0,
              chance_of_rain: 20,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_kph: 15,
              gust_mph: 9,
              uv: 4,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
              temp_c: 22,
              temp_f: 72,
              condition: {
                text: 'Light rain',
                icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
                code: 1183,
              },
              wind_kph: 12,
              wind_mph: 7,
              wind_dir: 'NW',
              pressure_mb: 1006,
              precip_mm: 1,
              precip_in: 0.04,
              humidity: 75,
              cloud: 70,
              feelslike_c: 24,
              feelslike_f: 75,
              windchill_c: 22,
              windchill_f: 72,
              heatindex_c: 24,
              heatindex_f: 75,
              dewpoint_c: 17,
              dewpoint_f: 63,
              will_it_rain: 1,
              chance_of_rain: 60,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 8,
              vis_miles: 5,
              gust_kph: 18,
              gust_mph: 11,
              uv: 2,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
              temp_c: 20,
              temp_f: 68,
              condition: {
                text: 'Light rain',
                icon: '//cdn.weatherapi.com/weather/64x64/night/296.png',
                code: 1183,
              },
              wind_kph: 15,
              wind_mph: 9,
              wind_dir: 'N',
              pressure_mb: 1005,
              precip_mm: 2,
              precip_in: 0.08,
              humidity: 80,
              cloud: 85,
              feelslike_c: 22,
              feelslike_f: 72,
              windchill_c: 20,
              windchill_f: 68,
              heatindex_c: 22,
              heatindex_f: 72,
              dewpoint_c: 16,
              dewpoint_f: 61,
              will_it_rain: 1,
              chance_of_rain: 70,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 7,
              vis_miles: 4,
              gust_kph: 20,
              gust_mph: 12,
              uv: 0,
              is_day: false,
            },
            {
              time: new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString(),
              temp_c: 18,
              temp_f: 64,
              condition: {
                text: 'Overcast',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_kph: 12,
              wind_mph: 7,
              wind_dir: 'NE',
              pressure_mb: 1004,
              precip_mm: 0,
              precip_in: 0,
              humidity: 85,
              cloud: 90,
              feelslike_c: 20,
              feelslike_f: 68,
              windchill_c: 18,
              windchill_f: 64,
              heatindex_c: 20,
              heatindex_f: 68,
              dewpoint_c: 15,
              dewpoint_f: 59,
              will_it_rain: 0,
              chance_of_rain: 30,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 6,
              vis_miles: 4,
              gust_kph: 16,
              gust_mph: 10,
              uv: 0,
              is_day: false,
            },
            {
              time: new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString(),
              temp_c: 16,
              temp_f: 61,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_kph: 8,
              wind_mph: 5,
              wind_dir: 'E',
              pressure_mb: 1003,
              precip_mm: 0,
              precip_in: 0,
              humidity: 80,
              cloud: 40,
              feelslike_c: 18,
              feelslike_f: 64,
              windchill_c: 16,
              windchill_f: 61,
              heatindex_c: 18,
              heatindex_f: 64,
              dewpoint_c: 12,
              dewpoint_f: 54,
              will_it_rain: 0,
              chance_of_rain: 10,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 8,
              vis_miles: 5,
              gust_kph: 12,
              gust_mph: 7,
              uv: 0,
              is_day: false,
            },
            {
              time: new Date(Date.now() + 11 * 60 * 60 * 1000).toISOString(),
              temp_c: 14,
              temp_f: 57,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_kph: 6,
              wind_mph: 4,
              wind_dir: 'SE',
              pressure_mb: 1002,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 20,
              feelslike_c: 16,
              feelslike_f: 61,
              windchill_c: 14,
              windchill_f: 57,
              heatindex_c: 16,
              heatindex_f: 61,
              dewpoint_c: 10,
              dewpoint_f: 50,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 8,
              gust_mph: 5,
              uv: 0,
              is_day: false,
            },
            {
              time: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
              temp_c: 12,
              temp_f: 54,
              condition: {
                text: 'Clear',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_kph: 4,
              wind_mph: 2,
              wind_dir: 'S',
              pressure_mb: 1001,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 10,
              feelslike_c: 14,
              feelslike_f: 57,
              windchill_c: 12,
              windchill_f: 54,
              heatindex_c: 14,
              heatindex_f: 57,
              dewpoint_c: 8,
              dewpoint_f: 46,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_kph: 6,
              gust_mph: 4,
              uv: 0,
              is_day: false,
            },
          ],
        },
        {
          date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
          day: {
            maxtemp_c: 23,
            maxtemp_f: 73,
            mintemp_c: 16,
            mintemp_f: 61,
            avgtemp_c: 19.5,
            avgtemp_f: 67.1,
            maxwind_kph: 18,
            maxwind_mph: 11,
            totalprecip_mm: 5,
            totalprecip_in: 0.2,
            avgvis_km: 8,
            avgvis_miles: 5,
            avghumidity: 70,
            daily_chance_of_rain: 60,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
              code: 1183,
            },
            uv: 3,
          },
          astro: {
            sunrise: '06:32 AM',
            sunset: '07:43 PM',
            moonrise: '09:20 PM',
            moonset: '07:50 AM',
            moon_phase: 'First Quarter',
            moon_illumination: '52',
          },
          hour: [
            {
              time: new Date(Date.now() + 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
              temp_c: 20,
              temp_f: 68,
              condition: {
                text: 'Light rain',
                icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
                code: 1183,
              },
              wind_kph: 15,
              wind_mph: 9,
              wind_dir: 'SW',
              pressure_mb: 1008,
              precip_mm: 2,
              precip_in: 0.08,
              humidity: 75,
              cloud: 80,
              feelslike_c: 22,
              feelslike_f: 72,
              windchill_c: 20,
              windchill_f: 68,
              heatindex_c: 22,
              heatindex_f: 72,
              dewpoint_c: 15,
              dewpoint_f: 59,
              will_it_rain: 1,
              chance_of_rain: 70,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 7,
              vis_miles: 4,
              gust_kph: 20,
              gust_mph: 12,
              uv: 3,
              is_day: true,
            },
            {
              time: new Date(Date.now() + 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
              temp_c: 21,
              temp_f: 70,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_kph: 12,
              wind_mph: 7,
              wind_dir: 'W',
              pressure_mb: 1009,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 45,
              feelslike_c: 23,
              feelslike_f: 73,
              windchill_c: 21,
              windchill_f: 70,
              heatindex_c: 23,
              heatindex_f: 73,
              dewpoint_c: 14,
              dewpoint_f: 57,
              will_it_rain: 0,
              chance_of_rain: 20,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_kph: 16,
              gust_mph: 10,
              uv: 5,
              is_day: true,
            },
          ],
        },
      ],
      lastUpdated: new Date().toISOString(),
    };

    return mockWeatherData;
  }

  // Real API implementation example (uncomment and modify as needed)
  /*
  private async fetchWeatherData(location: string, settings: WeatherSettings): Promise<WeatherData> {
    const response = await fetch(
      `${WEATHER_API_BASE_URL}/forecast.json?key=${WEATHER_API_KEY}&q=${encodeURIComponent(location)}&days=3&aqi=no`
    );

    if (!response.ok) {
      throw new Error(`Weather API error: ${response.status}`);
    }

    const data = await response.json();
    
    return {
      location: {
        name: data.location.name,
        region: data.location.region,
        country: data.location.country,
        lat: data.location.lat,
        lon: data.location.lon,
        timezone: data.location.tz_id,
        localtime: data.location.localtime,
      },
      current: {
        temp_c: data.current.temp_c,
        temp_f: data.current.temp_f,
        condition: data.current.condition,
        humidity: data.current.humidity,
        wind_kph: data.current.wind_kph,
        wind_mph: data.current.wind_mph,
        wind_dir: data.current.wind_dir,
        pressure_mb: data.current.pressure_mb,
        feelslike_c: data.current.feelslike_c,
        feelslike_f: data.current.feelslike_f,
        uv: data.current.uv,
        visibility_km: data.current.vis_km,
        cloud: data.current.cloud,
        is_day: data.current.is_day === 1,
      },
      forecast: data.forecast?.forecastday?.map((day: any) => ({
        date: day.date,
        day: {
          maxtemp_c: day.day.maxtemp_c,
          maxtemp_f: day.day.maxtemp_f,
          mintemp_c: day.day.mintemp_c,
          mintemp_f: day.day.mintemp_f,
          avgtemp_c: day.day.avgtemp_c,
          avgtemp_f: day.day.avgtemp_f,
          maxwind_kph: day.day.maxwind_kph,
          maxwind_mph: day.day.maxwind_mph,
          totalprecip_mm: day.day.totalprecip_mm,
          totalprecip_in: day.day.totalprecip_in,
          avgvis_km: day.day.avgvis_km,
          avgvis_miles: day.day.avgvis_miles,
          avghumidity: day.day.avghumidity,
          daily_chance_of_rain: day.day.daily_chance_of_rain,
          daily_chance_of_snow: day.day.daily_chance_of_snow,
          condition: day.day.condition,
          uv: day.day.uv,
        },
        astro: day.astro,
        hour: day.hour || [],
      })),
      lastUpdated: new Date().toISOString(),
    };
  }
  */

  clearCache(): void {
    this.cache.clear();
  }

  getCachedData(location: string, settings: WeatherSettings): WeatherData | null {
    const cacheKey = `${location}-${settings.unit}`;
    const cached = this.cache.get(cacheKey);
    
    if (cached && Date.now() - cached.timestamp < this.CACHE_DURATION) {
      return cached.data;
    }
    
    return null;
  }
}

export const weatherService = WeatherService.getInstance(); 